/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contacts.enterprise.manager.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import contacts.enterprise.manager.model.SupportMessage;
import contacts.enterprise.manager.model.SupportMessageModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SupportMessage service. Represents a row in the &quot;CEM_SupportMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SupportMessageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportMessageImpl
 * @generated
 */
public class SupportMessageModelImpl
	extends BaseModelImpl<SupportMessage> implements SupportMessageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support message model instance should use the <code>SupportMessage</code> interface instead.
	 */
	public static final String TABLE_NAME = "CEM_SupportMessage";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"messageId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"senderName", Types.VARCHAR}, {"senderEmail", Types.VARCHAR},
		{"subject", Types.VARCHAR}, {"body", Types.VARCHAR},
		{"replyText", Types.VARCHAR}, {"isReplied", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("messageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("senderName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("senderEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("body", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("replyText", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isReplied", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CEM_SupportMessage (uuid_ VARCHAR(75) null,messageId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,senderName VARCHAR(75) null,senderEmail VARCHAR(75) null,subject VARCHAR(75) null,body VARCHAR(75) null,replyText VARCHAR(75) null,isReplied BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table CEM_SupportMessage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY supportMessage.messageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CEM_SupportMessage.messageId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISREPLIED_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MESSAGEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SupportMessageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _messageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMessageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _messageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupportMessage.class;
	}

	@Override
	public String getModelClassName() {
		return SupportMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SupportMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SupportMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportMessage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SupportMessage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SupportMessage, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SupportMessage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SupportMessage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SupportMessage, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SupportMessage, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SupportMessage>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SupportMessage.class.getClassLoader(), SupportMessage.class,
			ModelWrapper.class);

		try {
			Constructor<SupportMessage> constructor =
				(Constructor<SupportMessage>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<SupportMessage, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SupportMessage, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SupportMessage, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SupportMessage, Object>>();
		Map<String, BiConsumer<SupportMessage, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SupportMessage, ?>>();

		attributeGetterFunctions.put("uuid", SupportMessage::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<SupportMessage, String>)SupportMessage::setUuid);
		attributeGetterFunctions.put("messageId", SupportMessage::getMessageId);
		attributeSetterBiConsumers.put(
			"messageId",
			(BiConsumer<SupportMessage, Long>)SupportMessage::setMessageId);
		attributeGetterFunctions.put("groupId", SupportMessage::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SupportMessage, Long>)SupportMessage::setGroupId);
		attributeGetterFunctions.put("companyId", SupportMessage::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SupportMessage, Long>)SupportMessage::setCompanyId);
		attributeGetterFunctions.put("userId", SupportMessage::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SupportMessage, Long>)SupportMessage::setUserId);
		attributeGetterFunctions.put("userName", SupportMessage::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SupportMessage, String>)SupportMessage::setUserName);
		attributeGetterFunctions.put(
			"createDate", SupportMessage::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SupportMessage, Date>)SupportMessage::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SupportMessage::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SupportMessage, Date>)SupportMessage::setModifiedDate);
		attributeGetterFunctions.put(
			"senderName", SupportMessage::getSenderName);
		attributeSetterBiConsumers.put(
			"senderName",
			(BiConsumer<SupportMessage, String>)SupportMessage::setSenderName);
		attributeGetterFunctions.put(
			"senderEmail", SupportMessage::getSenderEmail);
		attributeSetterBiConsumers.put(
			"senderEmail",
			(BiConsumer<SupportMessage, String>)SupportMessage::setSenderEmail);
		attributeGetterFunctions.put("subject", SupportMessage::getSubject);
		attributeSetterBiConsumers.put(
			"subject",
			(BiConsumer<SupportMessage, String>)SupportMessage::setSubject);
		attributeGetterFunctions.put("body", SupportMessage::getBody);
		attributeSetterBiConsumers.put(
			"body",
			(BiConsumer<SupportMessage, String>)SupportMessage::setBody);
		attributeGetterFunctions.put("replyText", SupportMessage::getReplyText);
		attributeSetterBiConsumers.put(
			"replyText",
			(BiConsumer<SupportMessage, String>)SupportMessage::setReplyText);
		attributeGetterFunctions.put("isReplied", SupportMessage::getIsReplied);
		attributeSetterBiConsumers.put(
			"isReplied",
			(BiConsumer<SupportMessage, Boolean>)SupportMessage::setIsReplied);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getMessageId() {
		return _messageId;
	}

	@Override
	public void setMessageId(long messageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_messageId = messageId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getSenderName() {
		if (_senderName == null) {
			return "";
		}
		else {
			return _senderName;
		}
	}

	@Override
	public void setSenderName(String senderName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_senderName = senderName;
	}

	@Override
	public String getSenderEmail() {
		if (_senderEmail == null) {
			return "";
		}
		else {
			return _senderEmail;
		}
	}

	@Override
	public void setSenderEmail(String senderEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_senderEmail = senderEmail;
	}

	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subject = subject;
	}

	@Override
	public String getBody() {
		if (_body == null) {
			return "";
		}
		else {
			return _body;
		}
	}

	@Override
	public void setBody(String body) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_body = body;
	}

	@Override
	public String getReplyText() {
		if (_replyText == null) {
			return "";
		}
		else {
			return _replyText;
		}
	}

	@Override
	public void setReplyText(String replyText) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_replyText = replyText;
	}

	@Override
	public boolean getIsReplied() {
		return _isReplied;
	}

	@Override
	public boolean isIsReplied() {
		return _isReplied;
	}

	@Override
	public void setIsReplied(boolean isReplied) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isReplied = isReplied;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsReplied() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isReplied"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SupportMessage.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SupportMessage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupportMessage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SupportMessage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupportMessageImpl supportMessageImpl = new SupportMessageImpl();

		supportMessageImpl.setUuid(getUuid());
		supportMessageImpl.setMessageId(getMessageId());
		supportMessageImpl.setGroupId(getGroupId());
		supportMessageImpl.setCompanyId(getCompanyId());
		supportMessageImpl.setUserId(getUserId());
		supportMessageImpl.setUserName(getUserName());
		supportMessageImpl.setCreateDate(getCreateDate());
		supportMessageImpl.setModifiedDate(getModifiedDate());
		supportMessageImpl.setSenderName(getSenderName());
		supportMessageImpl.setSenderEmail(getSenderEmail());
		supportMessageImpl.setSubject(getSubject());
		supportMessageImpl.setBody(getBody());
		supportMessageImpl.setReplyText(getReplyText());
		supportMessageImpl.setIsReplied(isIsReplied());

		supportMessageImpl.resetOriginalValues();

		return supportMessageImpl;
	}

	@Override
	public SupportMessage cloneWithOriginalValues() {
		SupportMessageImpl supportMessageImpl = new SupportMessageImpl();

		supportMessageImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		supportMessageImpl.setMessageId(
			this.<Long>getColumnOriginalValue("messageId"));
		supportMessageImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		supportMessageImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		supportMessageImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		supportMessageImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		supportMessageImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		supportMessageImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		supportMessageImpl.setSenderName(
			this.<String>getColumnOriginalValue("senderName"));
		supportMessageImpl.setSenderEmail(
			this.<String>getColumnOriginalValue("senderEmail"));
		supportMessageImpl.setSubject(
			this.<String>getColumnOriginalValue("subject"));
		supportMessageImpl.setBody(this.<String>getColumnOriginalValue("body"));
		supportMessageImpl.setReplyText(
			this.<String>getColumnOriginalValue("replyText"));
		supportMessageImpl.setIsReplied(
			this.<Boolean>getColumnOriginalValue("isReplied"));

		return supportMessageImpl;
	}

	@Override
	public int compareTo(SupportMessage supportMessage) {
		long primaryKey = supportMessage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SupportMessage)) {
			return false;
		}

		SupportMessage supportMessage = (SupportMessage)object;

		long primaryKey = supportMessage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SupportMessage> toCacheModel() {
		SupportMessageCacheModel supportMessageCacheModel =
			new SupportMessageCacheModel();

		supportMessageCacheModel.uuid = getUuid();

		String uuid = supportMessageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			supportMessageCacheModel.uuid = null;
		}

		supportMessageCacheModel.messageId = getMessageId();

		supportMessageCacheModel.groupId = getGroupId();

		supportMessageCacheModel.companyId = getCompanyId();

		supportMessageCacheModel.userId = getUserId();

		supportMessageCacheModel.userName = getUserName();

		String userName = supportMessageCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			supportMessageCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			supportMessageCacheModel.createDate = createDate.getTime();
		}
		else {
			supportMessageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			supportMessageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			supportMessageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		supportMessageCacheModel.senderName = getSenderName();

		String senderName = supportMessageCacheModel.senderName;

		if ((senderName != null) && (senderName.length() == 0)) {
			supportMessageCacheModel.senderName = null;
		}

		supportMessageCacheModel.senderEmail = getSenderEmail();

		String senderEmail = supportMessageCacheModel.senderEmail;

		if ((senderEmail != null) && (senderEmail.length() == 0)) {
			supportMessageCacheModel.senderEmail = null;
		}

		supportMessageCacheModel.subject = getSubject();

		String subject = supportMessageCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			supportMessageCacheModel.subject = null;
		}

		supportMessageCacheModel.body = getBody();

		String body = supportMessageCacheModel.body;

		if ((body != null) && (body.length() == 0)) {
			supportMessageCacheModel.body = null;
		}

		supportMessageCacheModel.replyText = getReplyText();

		String replyText = supportMessageCacheModel.replyText;

		if ((replyText != null) && (replyText.length() == 0)) {
			supportMessageCacheModel.replyText = null;
		}

		supportMessageCacheModel.isReplied = isIsReplied();

		return supportMessageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SupportMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SupportMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportMessage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SupportMessage)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SupportMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SupportMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportMessage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SupportMessage)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SupportMessage>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _messageId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _senderName;
	private String _senderEmail;
	private String _subject;
	private String _body;
	private String _replyText;
	private boolean _isReplied;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SupportMessage, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SupportMessage)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("messageId", _messageId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("senderName", _senderName);
		_columnOriginalValues.put("senderEmail", _senderEmail);
		_columnOriginalValues.put("subject", _subject);
		_columnOriginalValues.put("body", _body);
		_columnOriginalValues.put("replyText", _replyText);
		_columnOriginalValues.put("isReplied", _isReplied);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("messageId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("senderName", 256L);

		columnBitmasks.put("senderEmail", 512L);

		columnBitmasks.put("subject", 1024L);

		columnBitmasks.put("body", 2048L);

		columnBitmasks.put("replyText", 4096L);

		columnBitmasks.put("isReplied", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SupportMessage _escapedModel;

}