/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contacts.enterprise.manager.model.impl;

import contacts.enterprise.manager.model.SupportMessage;
import contacts.enterprise.manager.service.SupportMessageLocalServiceUtil;

/**
 * The extended model base implementation for the SupportMessage service. Represents a row in the &quot;CEM_SupportMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportMessageImpl
 * @see SupportMessage
 * @generated
 */
public abstract class SupportMessageBaseImpl
	extends SupportMessageModelImpl implements SupportMessage {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support message model instance should use the <code>SupportMessage</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SupportMessageLocalServiceUtil.addSupportMessage(this);
		}
		else {
			SupportMessageLocalServiceUtil.updateSupportMessage(this);
		}
	}

}