/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contacts.enterprise.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SupportMessage service. Represents a row in the &quot;CEM_SupportMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>contacts.enterprise.manager.model.impl.SupportMessageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>contacts.enterprise.manager.model.impl.SupportMessageImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportMessage
 * @generated
 */
@ProviderType
public interface SupportMessageModel
	extends BaseModel<SupportMessage>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support message model instance should use the {@link SupportMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this support message.
	 *
	 * @return the primary key of this support message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support message.
	 *
	 * @param primaryKey the primary key of this support message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this support message.
	 *
	 * @return the uuid of this support message
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this support message.
	 *
	 * @param uuid the uuid of this support message
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the message ID of this support message.
	 *
	 * @return the message ID of this support message
	 */
	public long getMessageId();

	/**
	 * Sets the message ID of this support message.
	 *
	 * @param messageId the message ID of this support message
	 */
	public void setMessageId(long messageId);

	/**
	 * Returns the group ID of this support message.
	 *
	 * @return the group ID of this support message
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this support message.
	 *
	 * @param groupId the group ID of this support message
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this support message.
	 *
	 * @return the company ID of this support message
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this support message.
	 *
	 * @param companyId the company ID of this support message
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this support message.
	 *
	 * @return the user ID of this support message
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this support message.
	 *
	 * @param userId the user ID of this support message
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this support message.
	 *
	 * @return the user uuid of this support message
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this support message.
	 *
	 * @param userUuid the user uuid of this support message
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this support message.
	 *
	 * @return the user name of this support message
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this support message.
	 *
	 * @param userName the user name of this support message
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this support message.
	 *
	 * @return the create date of this support message
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this support message.
	 *
	 * @param createDate the create date of this support message
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this support message.
	 *
	 * @return the modified date of this support message
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this support message.
	 *
	 * @param modifiedDate the modified date of this support message
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sender name of this support message.
	 *
	 * @return the sender name of this support message
	 */
	@AutoEscape
	public String getSenderName();

	/**
	 * Sets the sender name of this support message.
	 *
	 * @param senderName the sender name of this support message
	 */
	public void setSenderName(String senderName);

	/**
	 * Returns the sender email of this support message.
	 *
	 * @return the sender email of this support message
	 */
	@AutoEscape
	public String getSenderEmail();

	/**
	 * Sets the sender email of this support message.
	 *
	 * @param senderEmail the sender email of this support message
	 */
	public void setSenderEmail(String senderEmail);

	/**
	 * Returns the subject of this support message.
	 *
	 * @return the subject of this support message
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this support message.
	 *
	 * @param subject the subject of this support message
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this support message.
	 *
	 * @return the body of this support message
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this support message.
	 *
	 * @param body the body of this support message
	 */
	public void setBody(String body);

	/**
	 * Returns the reply text of this support message.
	 *
	 * @return the reply text of this support message
	 */
	@AutoEscape
	public String getReplyText();

	/**
	 * Sets the reply text of this support message.
	 *
	 * @param replyText the reply text of this support message
	 */
	public void setReplyText(String replyText);

	/**
	 * Returns the is replied of this support message.
	 *
	 * @return the is replied of this support message
	 */
	public boolean getIsReplied();

	/**
	 * Returns <code>true</code> if this support message is is replied.
	 *
	 * @return <code>true</code> if this support message is is replied; <code>false</code> otherwise
	 */
	public boolean isIsReplied();

	/**
	 * Sets whether this support message is is replied.
	 *
	 * @param isReplied the is replied of this support message
	 */
	public void setIsReplied(boolean isReplied);

	@Override
	public SupportMessage cloneWithOriginalValues();

}