##
## Check GETTING_STARTED.md for additional properties and their default values.
##

liferay.workspace.bundle.dist.include.metadata = true
liferay.workspace.modules.dir = modules
liferay.workspace.themes.dir = themes
liferay.workspace.wars.dir = modules
microsoft.translator.subscription.key = 
liferay.workspace.product = portal-7.4-ga31
target.platform.index.sources = false
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.29.7-hotspot
org.gradle.jvmargs=-Djdk.util.zip.disableZip64ExtraFieldValidation=true
com.liferay.portal.tools.service.builder.version=1.0.410
liferay.workspace.home.dir=C:/Users/jacop/Downloads/liferay-ce-portal-tomcat-7.4.3.31-ga31-20220628171544529/liferay-ce-portal-7.4.3.31-ga31